import { useEffect, useMemo, useState } from 'react'
import { fetchAdminCustomerDetails, fetchAdminCustomerLoyalty } from '../../services/customerService.js'
import './CustomerDetails.css'

const MONEY = new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP', maximumFractionDigits: 0 })
const DATE = new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
const STATUSES = ['All Status', 'pending', 'confirmed', 'preparing', 'ready', 'completed', 'cancelled', 'rejected']
const title = (value) => String(value || '').split(/[_\s-]+/).filter(Boolean).map((word) => word[0].toUpperCase() + word.slice(1).toLowerCase()).join(' ')
const date = (value) => value && !Number.isNaN(new Date(value).getTime()) ? DATE.format(new Date(value)) : '—'
const number = (order) => order.order_number || `#SB-${String(order.id || '').replace(/-/g, '').slice(0, 8).toUpperCase()}`
const initials = (customer) => [customer.first_name, customer.last_name].filter(Boolean).map((part) => part[0]).join('').slice(0, 2).toUpperCase() || 'CU'

export default function CustomerDetails({ customerId, onNavigate }) {
  const [customer, setCustomer] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [loyalty, setLoyalty] = useState(null); const [loyaltyError, setLoyaltyError] = useState(false)
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('All Status'); const [page, setPage] = useState(1); const [rows, setRows] = useState(10)
  useEffect(() => { let mounted = true; fetchAdminCustomerDetails(customerId).then((value) => { if (mounted) setCustomer(value) }).catch(() => { if (mounted) setError('Unable to load this customer.') }).finally(() => { if (mounted) setLoading(false) }); fetchAdminCustomerLoyalty(customerId).then((value) => { if (mounted) setLoyalty(value) }).catch(() => { if (mounted) setLoyaltyError(true) }); return () => { mounted = false } }, [customerId])
  const orders = useMemo(() => (customer?.orders || []).filter((order) => (!search || number(order).toLowerCase().includes(search.toLowerCase())) && (status === 'All Status' || order.order_status === status)), [customer, search, status])
  const pageCount = Math.max(1, Math.ceil(orders.length / rows)); const currentPage = Math.min(page, pageCount); const visible = orders.slice((currentPage - 1) * rows, currentPage * rows)
  if (loading) return <section className="admin-page admin-customer-details-page"><p>Loading customer details...</p></section>
  if (error || !customer) return <section className="admin-page admin-customer-details-page"><button className="customer-details-back" type="button" onClick={() => onNavigate('/admin/customers')}>← Back to Customers</button><p className="customer-details-error">{error || 'Customer not found.'}</p></section>
  const name = [customer.first_name, customer.last_name].filter(Boolean).join(' ') || customer.email || 'Customer'; const stats = customer.stats; const history = Array.isArray(loyalty?.history) ? loyalty.history : []
  const loyaltySection = <section className="customer-details-loyalty"><h3>Loyalty Rewards</h3><p>Every 2 completed orders earns 1 reward for 20% off one custom-order down payment.</p>{loyaltyError ? <p className="customer-details-loyalty-error">Unable to load loyalty information.</p> : loyalty ? <><div className="customer-details-loyalty-metrics"><div><span>Completed Orders</span><b>{loyalty.completed_orders}</b></div><div><span>Progress to Next Reward</span><b>{loyalty.progress} / {loyalty.threshold}</b></div><div><span>Available Rewards</span><b>{loyalty.available_rewards}</b></div><div><span>Reserved Rewards</span><b>{loyalty.reserved_rewards}</b></div><div><span>Used Rewards</span><b>{loyalty.used_rewards}</b></div></div><h4>Reward History</h4>{history.length ? <div className="customer-details-table-wrap"><table className="customer-details-table"><thead><tr><th>Cycle</th><th>Status</th><th>Earned</th><th>Used / Reserved</th><th>Order</th></tr></thead><tbody>{history.map((reward) => <tr key={reward.cycle_number}><td>{reward.cycle_number}</td><td><span className="customer-details-badge">{title(reward.status)}</span></td><td>{date(reward.earned_at)}</td><td>{date(reward.used_at || reward.reserved_at)}</td><td>{reward.related_order_number || '—'}</td></tr>)}</tbody></table></div> : <p className="customer-details-loyalty-empty">No loyalty rewards earned yet.</p>}</> : null}</section>
  return <section className="admin-page admin-customer-details-page">
    {loyaltySection}
    <button className="customer-details-back" type="button" onClick={() => onNavigate('/admin/customers')}>← Back to Customers</button>
    <div className="customer-details-heading"><div><p className="customer-details-eyebrow">Customers</p><h2>Customer Details</h2></div><span className="customer-details-status">{stats.validOrderCount ? 'Active' : 'Inactive'}</span></div>
    <section className="customer-details-overview"><div className="customer-details-identity"><span className="customer-details-avatar">{initials(customer)}</span><div><h3>{name}</h3><p>{customer.email || '—'}</p></div></div><div className="customer-details-info"><h4>Customer Profile</h4><p>Account Created: <b>{date(customer.created_at)}</b></p><p>Contact Number: <b>{stats.latestContactNumber || '—'}</b></p><p>Name: <b>{name}</b></p></div><div className="customer-details-info"><h4>Order Summary</h4><p>Total Orders: <b>{stats.validOrderCount}</b></p><p>Total Spent: <b>{MONEY.format(stats.totalSpent)}</b></p><p>Last Order: <b>{date(stats.lastOrder?.created_at)}</b></p></div></section>
    <section className="customer-details-orders"><div className="customer-details-orders-heading"><div><h3>All Orders</h3><p>{orders.length} of {stats.validOrderCount} orders</p></div><div className="customer-details-order-filters"><input aria-label="Search orders by order ID" placeholder="Search order ID..." value={search} onChange={(event) => { setSearch(event.target.value); setPage(1) }} /><select aria-label="Filter orders by status" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1) }}>{STATUSES.map((value) => <option key={value} value={value}>{value === 'All Status' ? value : title(value)}</option>)}</select></div></div><div className="customer-details-table-wrap"><table className="customer-details-table"><thead><tr><th>Order ID</th><th>Date</th><th>Category / Order</th><th>Fulfillment Status</th><th>Payment Status</th><th>Total</th><th>Action</th></tr></thead><tbody>{visible.length ? visible.map((order) => <tr key={order.id}><td>{number(order)}</td><td>{date(order.created_at)}</td><td>{(order.order_items || []).map((item) => item.product_name || item.product_type).filter(Boolean).join(', ') || 'Order'}</td><td><span className="customer-details-badge">{title(order.order_status) || 'Pending'}</span></td><td><span className="customer-details-badge">{title(order.payment_status) || 'Unpaid'}</span></td><td>{order.order_status === 'pending' && Number(order.total) === 0 ? 'Price Pending' : MONEY.format(Number(order.total) || 0)}</td><td><button type="button" className="customer-details-view" onClick={() => onNavigate('/admin/orders')}>View Order</button></td></tr>) : <tr><td colSpan="7" className="customer-details-empty">No orders found.</td></tr>}</tbody></table></div><div className="customer-details-pagination"><span>Showing {orders.length ? (currentPage - 1) * rows + 1 : 0}–{Math.min(currentPage * rows, orders.length)} of {orders.length} orders</span><label>Rows per page: <select value={rows} onChange={(event) => { setRows(Number(event.target.value)); setPage(1) }}><option value="10">10</option><option value="15">15</option><option value="25">25</option></select></label><button type="button" disabled={currentPage <= 1} onClick={() => setPage(currentPage - 1)}>‹</button><span>{currentPage} / {pageCount}</span><button type="button" disabled={currentPage >= pageCount} onClick={() => setPage(currentPage + 1)}>›</button></div></section>
  </section>
}
